spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    name: courseManagementDb
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password